### ISSUE TITLE
Add SMTP server

### ISSUE THREAD

**Issue by ishbir** [monetas/bmclient#5]
The SMTP we add will need some sort of a dispatcher to route messages based on the recipient:
- Normal person-to-person messages (sent to BM-someaddress@bm.addr)
- Broadcasts (sent to broadcast@bm.addr)
- Control messages (sent to bmclient@bm.addr)

The first two cases are simple and don't need any special rules except for maybe when using chans. If we are sending to a chan (keymgr.ID.IsChan == true), no Ack should be generated.

Control messages should accomplish things that cannot otherwise be done in bmclient. This includes:
- Subscribing to broadcast addresses
- Subscribing to chans
- Generating a new HD identity.

Responses to these requests could be put in a separate folder in IMAP called Bmclient (maybe), to avoid cluttering Inbox with non-messages.

**Comment by DanielKrawisz** [comment]
The stuff I've already written for bitmessages doesn't need to distinguish a separate case for broadcasts vs messages. There is a GenerateObject func that just generates the correct wire.Object struct that can be sent out in the network. 

As to the 3rd case, we should just have an object that handles control messages and generates the appropriate response. And yes, there should be a special folder for those. I would probably call the folder Control.
