### ISSUE TITLE
Store number of times a public key was requested. 

### ISSUE THREAD

**Issue by DanielKrawisz** [monetas/bmclient#6]
Right now the public key request store simply stores the last time that a public key was requested. If a request times out, we might want to send more public key requests, but stop after a few more times. We should also want to store addresses that have failed ever to return a pub key so that we know not to send messages to it again.

**Comment by ishbir** [comment]
I agree. But I don't think we need to separately maintain a list of addresses that have failed to ever return a pubkey. This information could just be derived from the number of times that a pubkey was requested. We could set a threshold value, let's say 5, after which a pubkey is never requested again. If a pubkey is received, it should be removed from this store.
